name: custom_container_animated
description: "A Flutter package to create animated containers with various customizable animations."
version: 0.0.1
homepage: https://github.com/harshit7132/custom_container_animated.git # Add your homepage URL or a GitHub repository link

environment:
  sdk: ">=2.17.0 <3.0.0" # Adjusted to a more general SDK constraint for compatibility
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see
# the following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# If you have any assets (images, etc.), you can list them here.
# For now, no assets are specified.
# assets:
#   - images/a_dot_burr.jpeg

# Fonts (if you are using custom fonts, list them here)
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
