name: custom_container_animated
description: "A Flutter package to create animated containers with various customizable animations."
version: 0.0.1
homepage: https://github.com/harshit7132/custom_container_animated  # Your repository URL

environment:
  sdk: ">=2.17.0 <3.0.0"  # Flutter SDK constraints
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

license: MIT  # Specify the license type

flutter:
# If your package uses assets, list them here.
# assets:
#   - images/a_dot_burr.jpeg

# If your package uses fonts, list them here.
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
